#!/bin/bash
pip install -e ./jupyter-gfort-kernel
jupyter kernelspec install ./jupyter-gfort-kernel/gfort_spec --user
wget https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
tar zxvf julia-1.1.1-linux-x86_64.tar.gz
export PATH=$PATH:~/julia-1.1.1/bin
julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.add("Plots"); Pkg.update(); Pkg.build(); Pkg.precompile()'
rm julia-1.1.1-linux-x86_64.tar.gz
jupyter contrib nbextension install --user
mkdir flang
cd flang
wget https://github.com/flang-compiler/flang/releases/download/flang_20190329/flang-20190329-x86-70.tgz
tar zxvf flang-20190329-x86-70.tgz
rm flang-20190329-x86-70.tgz
cd ..
wget 'https://sourceforge.net/projects/schur/files/Debian%20package/6.10/schur_6.10-2_amd64.deb'
dpkg -x  ./schur_6.10-2_amd64.deb /      
echo export LD_LIBRARY_PATH=~/flang/lib:$LD_LIBRARY_PATH >> ~/.bashrc
echo export PATH=~/flang/bin:$PATH                       >> ~/.bashrc

