#!/bin/bash
pip install -e ./jupyter-gfort-kernel
jupyter kernelspec install ./jupyter-gfort-kernel/gfort_spec --user
wget https://julialang-s3.julialang.org/bin/linux/x64/1.1/julia-1.1.1-linux-x86_64.tar.gz
tar zxvf julia-1.1.1-linux-x86_64.tar.gz
export PATH=$PATH:~/julia-1.1.1/bin
julia -e 'using Pkg; Pkg.add("IJulia"); Pkg.add("Plots"); Pkg.update(); Pkg.build(); Pkg.precompile()'
rm julia-1.1.1-linux-x86_64.tar.gz
jupyter contrib nbextension install --user
mkdir flang
cd flang
wget https://github.com/flang-compiler/flang/releases/download/flang_20190329/flang-20190329-x86-70.tgz
tar zxvf flang-20190329-x86-70.tgz
rm flang-20190329-x86-70.tgz
cd ..
mkdir schur
cd schur
wget https://sourceforge.net/projects/schur/files/Debian%20package/6.10/schur_6.10-2_amd64.deb
dpkg -x ./schur_6.10-2_amd64.deb .
rm schur_6.10-2_amd64.deb   
wget http://http.us.debian.org/debian/pool/main/r/readline6/libreadline6_6.3-8+b3_amd64.deb
dpkg -x libreadline6_6.3-8+b3_amd64.deb
rm libreadline6_6.3-8+b3_amd64.deb   
cd ..
echo export SCHURLIB=~/schur/usr/share/schur  >>~/.bashrc  
echo export LD_LIBRARY_PATH=~/flang/lib:~/schur/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH >> ~/.bashrc
echo export PATH=~/flang/bin:~/schur/usr/bin:$PATH             >> ~/.bashrc

